allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  prisma: false
  sharp: false
  unrs-resolver: false
overrides:
  brace-expansion@<1.1.18: ^1.1.18
  brace-expansion@>=4.0.0 <5.0.9: ^5.0.9
  js-yaml@>=4.0.0 <4.3.1: ^4.3.1
  js-yaml@>=4.0.0 <4.3.2: ^4.3.2
  nanoid@<3.3.18: ^3.3.18
  next@>=10.0.0 <15.5.24: ^15.5.24
  next@>=13.4.0 <15.5.24: ^15.5.24
  postcss@<8.5.10: ^8.5.10
  postcss@<=8.5.11: ^8.5.12
  postcss@<=8.5.17: ^8.5.18
  postcss@<=8.5.22: ^8.5.23
  sharp@<0.35.0: ^0.35.0
  sharp@<0.35.4: ^0.35.4
