import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#636561",
        "inverse-on-surface": "#313030",
        "surface-variant": "#353534",
        "on-primary": "var(--on-primary)",
        "tertiary-container": "#e8e1e0",
        "error": "var(--error)",
        "on-primary-fixed": "#1a1c19",
        "on-error-container": "#ffdad6",
        "surface-bright": "#3a3938",
        "inverse-primary": "#5d5f5b",
        "on-tertiary-fixed-variant": "#494646",
        "background": "var(--background)",
        "surface-tint": "#c6c7c2",
        "on-surface-variant": "#7e7576",
        "primary-fixed": "#e2e3de",
        "secondary": "#c8c6c9",
        "on-secondary-container": "#b6b4b8",
        "on-secondary": "#303033",
        "primary-container": "#e2e3de",
        "surface-dim": "#141313",
        "surface-container-highest": "#353534",
        "on-error": "var(--on-error)",
        "tertiary": "#ffffff",
        "secondary-fixed": "#e4e1e5",
        "on-secondary-fixed-variant": "#47464a",
        "secondary-fixed-dim": "#c8c6c9",
        "outline": "var(--outline)",
        "surface-container": "#201f1f",
        "on-background": "var(--on-background)",
        "inverse-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#1d1b1b",
        "surface-container-low": "var(--surface-container-low)",
        "outline-variant": "#454843",
        "on-tertiary": "#33302f",
        "on-secondary-fixed": "#1b1b1e",
        "on-surface": "var(--on-background)",
        "tertiary-fixed": "#e8e1e0",
        "tertiary-fixed-dim": "#cbc5c4",
        "primary-fixed-dim": "#c6c7c2",
        "primary": "var(--primary)",
        "on-primary-fixed-variant": "#454744",
        "secondary-container": "#47464a",
        "on-tertiary-container": "#676363",
        "surface": "var(--surface)",
        "error-container": "#93000a",
        "surface-container-high": "var(--surface-container-high)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max-width": "1280px",
        "container-max": "1280px",
        "base": "4px",
        "gutter": "24px",
        "margin-sm": "16px",
        "margin-md": "32px",
        "margin-lg": "64px"
      },
      fontFamily: {
        "code": ["JetBrains Mono", "Geist", "monospace"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "serif": ["\"Source Serif 4\"", "serif"],
        "body": ["Geist", "Inter", "sans-serif"],
        "headline": ["\"Source Serif 4\"", "Inter", "serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [],
};
export default config;
